### ISSUE TITLE
Cannot install with Pytorch 1.8.0

### ISSUE THREAD

**Issue by zwx8981** [teddykoker/torchsort#12]
repanda_zwx@repandazwx:/home/rpanda$ conda activate iqa2
(iqa2) repanda_zwx@repandazwx:/home/rpanda$ pip install torchsort
ERROR: Could not find a version that satisfies the requirement torchsort
ERROR: No matching distribution found for torchsort
(iqa2) repanda_zwx@repandazwx:/home/rpanda$ python
Python 3.7.10 (default, Feb 26 2021, 18:47:35) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.__version__)
1.8.0
>>>

**Comment by teddykoker** [comment]
I believe this issue was because of the `python_requires=">=3.8"` line in `setup.py`. I have just pushed a new version (0.1.2) that supports >=3.7, so you should be able to install with no issues.

**Comment by zwx8981** [comment]
It works, thank you.

**Comment by valdersoul** [comment]
Hi, how about py3.6?

Thanks!
