### ISSUE TITLE
Couldn't compile using setup.py

### ISSUE THREAD

**Issue by awmulyadi** [teddykoker/torchsort#14]
Greetings. I would like to install this library to be incorporated in my current framework which required the GPU build. However, I bump into an issue when executing the `python setup.py install` with the following error messages:

``running install
running bdist_egg
running egg_info
writing torchsort.egg-info/PKG-INFO
writing dependency_links to torchsort.egg-info/dependency_links.txt
writing requirements to torchsort.egg-info/requires.txt
writing top-level names to torchsort.egg-info/top_level.txt
reading manifest file 'torchsort.egg-info/SOURCES.txt'
writing manifest file 'torchsort.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'torchsort.isotonic_cpu' extension
Emitting ninja build file /data/repositories/SVAE/torchsort/build/temp.linux-x86_64-3.7/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.8.2
x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fdebug-prefix-map=/build/python3.7-a56wZI/python3.7-3.7.10=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 /data/repositories/SVAE/torchsort/build/temp.linux-x86_64-3.7/torchsort/isotonic_cpu.o -L/data/repositories/SVAE/env/lib/python3.7/site-packages/torch/lib -lc10 -ltorch -ltorch_cpu -ltorch_python -o build/lib.linux-x86_64-3.7/torchsort/isotonic_cpu.cpython-37m-x86_64-linux-gnu.so
x86_64-linux-gnu-g++: error: /data/repositories/SVAE/torchsort/build/temp.linux-x86_64-3.7/torchsort/isotonic_cpu.o: No such file or directory
error: command 'x86_64-linux-gnu-g++' failed with exit status 1``

I believed that the compilation faced the error somehow, but without any explicit error message.
Following are my installed (possibly related) packages:
- Python 3.7.10
- torch 1.7.1
- torchvision 0.82
- CUDA version 11.0
- Nvidia Cuda Toolkit (NVCC) 11.2
- Ninja-Build 1.8.2

I am not sure whether this information is sufficient, please kindly give me hints.
Really appreciate your solution to solve this problem. 
Thanks!
Regards.

**Comment by teddykoker** [comment]
Hmm, when run the install I see the following files created in the build directory:
```
build
├── bdist.linux-x86_64
├── lib.linux-x86_64-3.8
│   └── torchsort
│       ├── __init__.py
│       ├── isotonic_cpu.cpp
│       ├── isotonic_cpu.cpython-38-x86_64-linux-gnu.so
│       ├── isotonic_cuda.cpython-38-x86_64-linux-gnu.so
│       ├── isotonic_cuda.cu
│       └── ops.py
└── temp.linux-x86_64-3.8
    ├── build.ninja
    └── torchsort
        ├── isotonic_cpu.o
        └── isotonic_cuda.o
```

It appears your installation is failing because the object file `isotonic_cpu.o`. It looks like it may be skipping a step where it compiles this object file. This is the portion of my output that is doing this:
```
c++ -MMD -MF /home/teddy/projects/torchsort/build/temp.linux-x86_64-3.8/torchsort/iso
tonic_cpu.o.d -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -
fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protecto
r-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/ted
dy/.local/lib/python3.8/site-packages/torch/include -I/home/teddy/.local/lib/python3.8/site
-packages/torch/include/torch/csrc/api/include -I/home/teddy/.local/lib/python3.8/site-pack
ages/torch/include/TH -I/home/teddy/.local/lib/python3.8/site-packages/torch/include/THC -I
/usr/include/python3.8 -c -c /home/teddy/projects/torchsort/torchsort/isotonic_cpu.cpp -o /
home/teddy/projects/torchsort/build/temp.linux-x86_64-3.8/torchsort/isotonic_cpu.o -fopenmp
 -ffast-math -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=isotonic_cpu -D_GLIBCXX
_USE_CXX11_ABI=0 -std=c++14
```
The following step is then performed, which appears to be near identical as yours above:
```
x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-funct
ions -Wl,-z,relro -g -fwrapv -O2 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -g -f
stack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 /ho
me/teddy/projects/torchsort/build/temp.linux-x86_64-3.8/torchsort/isotonic_cpu.o -L/home/te
ddy/.local/lib/python3.8/site-packages/torch/lib -lc10 -ltorch -ltorch_cpu -ltorch_python -
o build/lib.linux-x86_64-3.8/torchsort/isotonic_cpu.cpython-38-x86_64-linux-gnu.so
```
Except of course it runs successfully because the object file has been compiled. I am not sure exactly how to solve this issue but here are a few ideas:
 
  1. Remove the build directory and try again: `rm -rf build`
  2. Update or remove ninja (I have successfully installed without ninja and with version 1.10.0)
  3. Manually run the `c++` command; this seems like a bad idea but could work if all else fails.
 
Let me know if there is any more error output that could be useful in determining why the first compile step is failing. I have not run into any issues like this on any of my machines, nor Docker containers or CI systems. I hope to get this resolved as soon as I can!

**Comment by awmulyadi** [comment]
It seems the compilation was failed due to ninja in my current environment. I followed your first two steps (removed the ninja on the second step) and managed to build the library. Thanks for your hints. I really appreciate it.

Just in case for future reference, here is my log for a successful build.

`running install
running bdist_egg
running egg_info
writing torchsort.egg-info/PKG-INFO
writing dependency_links to torchsort.egg-info/dependency_links.txt
writing requirements to torchsort.egg-info/requires.txt
writing top-level names to torchsort.egg-info/top_level.txt
/data/repositories/SVAE/env/lib/python3.7/site-packages/torch/utils/cpp_extension.py:352: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
reading manifest file 'torchsort.egg-info/SOURCES.txt'
writing manifest file 'torchsort.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'torchsort.isotonic_cpu' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fdebug-prefix-map=/build/python3.7-a56wZI/python3.7-3.7.10=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/data/repositories/SVAE/env/lib/python3.7/site-packages/torch/include -I/data/repositories/SVAE/env/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/data/repositories/SVAE/env/lib/python3.7/site-packages/torch/include/TH -I/data/repositories/SVAE/env/lib/python3.7/site-packages/torch/include/THC -I/data/repositories/SVAE/env/include -I/usr/include/python3.7m -c torchsort/isotonic_cpu.cpp -o build/temp.linux-x86_64-3.7/torchsort/isotonic_cpu.o -fopenmp -ffast-math -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=isotonic_cpu -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fdebug-prefix-map=/build/python3.7-a56wZI/python3.7-3.7.10=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.7/torchsort/isotonic_cpu.o -L/data/repositories/SVAE/env/lib/python3.7/site-packages/torch/lib -lc10 -ltorch -ltorch_cpu -ltorch_python -o build/lib.linux-x86_64-3.7/torchsort/isotonic_cpu.cpython-37m-x86_64-linux-gnu.so
building 'torchsort.isotonic_cuda' extension
/usr/local/cuda-11.2/bin/nvcc -I/data/repositories/SVAE/env/lib/python3.7/site-packages/torch/include -I/data/repositories/SVAE/env/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/data/repositories/SVAE/env/lib/python3.7/site-packages/torch/include/TH -I/data/repositories/SVAE/env/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.2/include -I/data/repositories/SVAE/env/include -I/usr/include/python3.7m -c torchsort/isotonic_cuda.cu -o build/temp.linux-x86_64-3.7/torchsort/isotonic_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=isotonic_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_61,code=sm_61 -std=c++14
/data/repositories/SVAE/env/lib/python3.7/site-packages/torch/include/ATen/core/boxing/impl/boxing.h(100): warning: integer conversion resulted in a change of sign

/data/repositories/SVAE/env/lib/python3.7/site-packages/torch/include/ATen/core/op_registration/op_whitelist.h(39): warning: integer conversion resulted in a change of sign

/data/repositories/SVAE/env/lib/python3.7/site-packages/torch/include/ATen/core/boxing/impl/boxing.h(100): warning: integer conversion resulted in a change of sign

/data/repositories/SVAE/env/lib/python3.7/site-packages/torch/include/ATen/core/op_registration/op_whitelist.h(39): warning: integer conversion resulted in a change of sign

/data/repositories/SVAE/env/lib/python3.7/site-packages/torch/include/ATen/core/boxing/impl/boxing.h(100): warning: integer conversion resulted in a change of sign

/data/repositories/SVAE/env/lib/python3.7/site-packages/torch/include/ATen/core/op_registration/op_whitelist.h(39): warning: integer conversion resulted in a change of sign

/data/repositories/SVAE/env/lib/python3.7/site-packages/torch/include/ATen/core/boxing/impl/boxing.h(100): warning: integer conversion resulted in a change of sign

/data/repositories/SVAE/env/lib/python3.7/site-packages/torch/include/ATen/core/op_registration/op_whitelist.h(39): warning: integer conversion resulted in a change of sign

/data/repositories/SVAE/env/lib/python3.7/site-packages/torch/include/ATen/core/boxing/impl/boxing.h(100): warning: integer conversion resulted in a change of sign

/data/repositories/SVAE/env/lib/python3.7/site-packages/torch/include/ATen/core/op_registration/op_whitelist.h(39): warning: integer conversion resulted in a change of sign

x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fdebug-prefix-map=/build/python3.7-a56wZI/python3.7-3.7.10=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.7/torchsort/isotonic_cuda.o -L/data/repositories/SVAE/env/lib/python3.7/site-packages/torch/lib -L/usr/local/cuda-11.2/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-3.7/torchsort/isotonic_cuda.cpython-37m-x86_64-linux-gnu.so
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/torchsort
copying build/lib.linux-x86_64-3.7/torchsort/ops.py -> build/bdist.linux-x86_64/egg/torchsort
copying build/lib.linux-x86_64-3.7/torchsort/isotonic_cpu.cpp -> build/bdist.linux-x86_64/egg/torchsort
copying build/lib.linux-x86_64-3.7/torchsort/isotonic_cuda.cu -> build/bdist.linux-x86_64/egg/torchsort
copying build/lib.linux-x86_64-3.7/torchsort/isotonic_cuda.cpython-37m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/torchsort
copying build/lib.linux-x86_64-3.7/torchsort/isotonic_cpu.cpython-37m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/torchsort
copying build/lib.linux-x86_64-3.7/torchsort/__init__.py -> build/bdist.linux-x86_64/egg/torchsort
byte-compiling build/bdist.linux-x86_64/egg/torchsort/ops.py to ops.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/torchsort/__init__.py to __init__.cpython-37.pyc
creating stub loader for torchsort/isotonic_cpu.cpython-37m-x86_64-linux-gnu.so
creating stub loader for torchsort/isotonic_cuda.cpython-37m-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/torchsort/isotonic_cpu.py to isotonic_cpu.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/torchsort/isotonic_cuda.py to isotonic_cuda.cpython-37.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying torchsort.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying torchsort.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying torchsort.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying torchsort.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying torchsort.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
torchsort.__pycache__.isotonic_cpu.cpython-37: module references __file__
torchsort.__pycache__.isotonic_cuda.cpython-37: module references __file__
creating dist
creating 'dist/torchsort-0.1.2-py3.7-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing torchsort-0.1.2-py3.7-linux-x86_64.egg
creating /data/repositories/SVAE/env/lib/python3.7/site-packages/torchsort-0.1.2-py3.7-linux-x86_64.egg
Extracting torchsort-0.1.2-py3.7-linux-x86_64.egg to /data/repositories/SVAE/env/lib/python3.7/site-packages
Adding torchsort 0.1.2 to easy-install.pth file

Installed /data/repositories/SVAE/env/lib/python3.7/site-packages/torchsort-0.1.2-py3.7-linux-x86_64.egg
Processing dependencies for torchsort==0.1.2
Searching for torch==1.7.1
Best match: torch 1.7.1
Adding torch 1.7.1 to easy-install.pth file
Installing convert-caffe2-to-onnx script to /data/repositories/SVAE/env/bin
Installing convert-onnx-to-caffe2 script to /data/repositories/SVAE/env/bin

Using /data/repositories/SVAE/env/lib/python3.7/site-packages
Searching for numpy==1.18.5
Best match: numpy 1.18.5
Adding numpy 1.18.5 to easy-install.pth file
Installing f2py script to /data/repositories/SVAE/env/bin
Installing f2py3 script to /data/repositories/SVAE/env/bin
Installing f2py3.7 script to /data/repositories/SVAE/env/bin

Using /data/repositories/SVAE/env/lib/python3.7/site-packages
Searching for typing-extensions==3.7.4.3
Best match: typing-extensions 3.7.4.3
Adding typing-extensions 3.7.4.3 to easy-install.pth file

Using /data/repositories/SVAE/env/lib/python3.7/site-packages
Finished processing dependencies for torchsort==0.1.2`

**Comment by teddykoker** [comment]
Great to hear @awmulyadi! I am not sure there is anything I can do with the package to avoid problems like this, but hopefully this doesn't happen too frequently.
