### ISSUE TITLE
pip install failed in windows

### ISSUE THREAD

**Issue by Reasat** [teddykoker/torchsort#17]
Hi, I faced an installation error in windows. It installed fine in my ubuntu system. Could you tell me how I can fix it?

``` 
Internal error: assertion failed at: "C:/dvs/p4/build/sw/rel/gpu_drv/r400/r400_00/drivers/compiler/edg/EDG_4.14/
src/decl_spec.c", line 9596
    
    
    1 catastrophic error detected in the compilation of "C:/Users/Reasat/AppData/Local/Temp/tmpxft_000028b0_00000000
-5_isotonic_cuda.cpp4.ii".
    Compilation aborted.
    isotonic_cuda.cu
    nvcc error   : 'cudafe++' died with status 0xC0000409
    error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.0\\bin\\nvcc.exe' failed with exit st
atus 9
    Error in atexit._run_exitfuncs:
    Traceback (most recent call last):
      File "C:\Users\Reasat\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 59, in clos
ed
        return stream.closed
    ValueError: underlying buffer has been detached
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'D:\Miniconda3\envs\pytorch\python.exe' -u -c 'import sys, setuptools
, tokenize; sys.argv[0] = '"'"'C:\\Users\\Reasat\\AppData\\Local\\Temp\\pip-install-uw3b5i5w\\torchsort_f8d66d1aaac6
44a78d37585cc7273f94\\setup.py'"'"'; __file__='"'"'C:\\Users\\Reasat\\AppData\\Local\\Temp\\pip-install-uw3b5i5w\\to
rchsort_f8d66d1aaac644a78d37585cc7273f94\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.r
ead().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --recor
d 'C:\Users\Reasat\AppData\Local\Temp\pip-record-nbabfu8b\install-record.txt' --single-version-externally-managed --
compile --install-headers 'D:\Miniconda3\envs\pytorch\Include\torchsort' Check the logs for full command output.
```

**Comment by teddykoker** [comment]
Hi Reasat, this seems that it might be an issue with `colorama`  (looking at your traceback). A quick google and I find [this issue](https://github.com/tartley/colorama/issues/266) which appears to be unresolved. Maybe there is some sort of race condition with the stdout buffer? Perhaps if you have ninja installed you could try uninstalling it and try installing torchsort again, but I am not sure if this is related. Unfortunately I do not have access to a Windows system at the moment so I will be unable to reproduce.

**Comment by Reasat** [comment]
Thanks! I'll try the ninja uninstall thing when I get a chance.

**Comment by Reasat** [comment]
I don't have ninja installed in the conda environment. I created a new environment and installed only torch in there. Then tried to install torchsort, that also failed :(

**Comment by teddykoker** [comment]
Hmm is it failing to build the C++ extension as well? Or is it just the CUDA extension. I could potentially modify the setup.py file to add a flag to only optionally compile the CUDA extension if the user requests, but then of course you would not be able to use torchsort with cuda tensors.

Unfortunately without a windows machine with GPU I will have a hard time debugging this, but do keep me up to speed if you encounter any more clues as to why the build is failing.

**Comment by teddykoker** [comment]
Another thing you could try is installing the [pytorch example cpp repo](https://github.com/pytorch/extension-cpp) (instructions in README). If you run into the same issue there it could be an issue with the PyTorch build tools / your machine.

**Comment by Reasat** [comment]
Will try that out, thanks!
