### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by MaxChu719** [teddykoker/torchsort#22]
I got the below error when training my network for a while (10-20 epochs).
`Traceback (most recent call last):
  File "train.py", line 232, in <module>
    main()
  File "train.py", line 179, in main
    train(cfg, train_loader, model, criterion, optimizer, lr_scheduler, epoch, final_output_dir, tb_log_dir, writer_dict)
  File "/home/maxchu/Fin/numerai_dev/function.py", line 62, in train
    loss, loss_indv = criterion(pred, target, auto_pred, auto_target)
  File "/home/maxchu/fin_venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/maxchu/Fin/numerai_dev/loss.py", line 39, in forward
    - 0.1 * spearman(pred, target, regularization_strength=1e-2),
  File "/home/maxchu/Fin/numerai_dev/loss.py", line 24, in spearman
    pred = torchsort.soft_rank(
  File "/home/maxchu/fin_venv/lib/python3.8/site-packages/torchsort-0.1.4-py3.8-linux-x86_64.egg/torchsort/ops.py", line 40, in soft_rank
    return SoftRank.apply(values, regularization, regularization_strength)
  File "/home/maxchu/fin_venv/lib/python3.8/site-packages/torchsort-0.1.4-py3.8-linux-x86_64.egg/torchsort/ops.py", line 96, in forward
    ret = (s - dual_sol).gather(1, inv_permutation)
RuntimeError: CUDA error: an illegal memory access was encountered`
Some details:

1. System: Ubuntu 18.06
2. Python 3.8 using venv
2. Install method: Manual compile (git clone -> python setup.py install)
3. PyTorch 1.8.0 with cuda 10.2 (and correspinding pytorch geometric package)

Please let me know if you need more informations.

**Comment by teddykoker** [comment]
Hi!

`RuntimeError: CUDA error: an illegal memory access was encountered` is a fairly [generic error that can be caused by many different reasons](https://github.com/pytorch/pytorch/issues/21819#issuecomment-638493770) so this will be very hard to debug without having a script to reproduce the issue. If you could provide a minimal script that reproduces this issue that would be very helpful! If that is not possible you could try the following:

1. Ensure you aren't running out of memory
2. Ensure there are no `nan` values in your tensor
3. Maybe try updating to `torch==1.8.1`

It looks like the error is occuring on line 96 of ops.py:
```python
ret = (s - dual_sol).gather(1, inv_permutation)
```
So perhaps you could ensure that there are no `nan` values in `inv_permutation` and that `s`, `dual_sol` and `inv_permutation` have the same length.

**Comment by MaxChu719** [comment]
@teddykoker 
1. I am pretty sure it is not out of memory as I have tried using a different batch size
2. I am pretty sure there is no nan in the tensor but I can try to write a minimal scipt
3. I am using PyTorch geometric lib that does not have prebuild whl on torch==1.8.1, i will try manual build in last resort.

**Comment by MaxChu719** [comment]
@teddykoker below is the minimal program that reproduces the problem. I am test with GTX2080 GPUs (cuda:0 - cuda:3). 
`import torch
import torchsort
import numpy as np


def spearmanr(pred, target, **kw):
    pred = torchsort.soft_rank(pred, **kw)
    target = torchsort.soft_rank(target, **kw)
    pred = pred - pred.mean()
    pred = pred / pred.norm()
    target = target - target.mean()
    target = target / target.norm()
    return (pred * target).sum()


num_trial = 100000
batch_size = 5
num_dim = 1000
for r in range(num_trial):
    pred = torch.tensor(np.random.uniform(0, 1, [batch_size, num_dim]), requires_grad=True).to('cuda:3')
    target = torch.tensor(np.random.uniform(0, 1, [batch_size, num_dim])).to('cuda:3')
    spearman = spearmanr(pred, target)
    grad = torch.autograd.grad(spearman, pred)
    if r % 1000 == 1:
        print(r, spearman, grad)`

P.S. When I tried to test it on K80 (cuda:4 - cuda:7), I will get ```RuntimeError: CUDA error: invalid device function```, which is very strange as I can run my main training program using K80s only without this problem.

**Comment by MaxChu719** [comment]
@teddykoker I have some future experiments:

1. When I run the script with `cuda:0` but using the command `CUDA_VISIBLE_DEVICES=2 python minimal.py` (Using one of my 2080 GPU). The problem goes away.
2. When i run the script with `CUDA_VISIBLE_DEVICES=2 python minimal.py` (Using one of my K80 GPU), i will get `RuntimeError: CUDA error: no kernel image is available for execution on the device`

**Comment by teddykoker** [comment]
Hi @MaxChu719,

1. I currently only have access to a single 2070 GPU, which runs the code you provided without issue (using `cuda:0`). I am not sure why the behavior would be any different using a GPU with another index.

2. I believe this problem can be fixed during install of `torchsort` (which is when the kernel is compiled). Exporting environmental variable `TORCH_CUDA_ARCH_LIST="Tesla"` should inform to compile the proper kernel for your GPU.

Let me know if you have made any other discoveries, I do hope to resolve this!

**Comment by MaxChu719** [comment]
@teddykoker 
Thanks for the reply. I am currently using 2080 for my program. I think it is the K80 problem. I will try your sugguestion later to see if it solves the prpblem.
