### ISSUE TITLE
PyTorch 1.9 Crash

### ISSUE THREAD

**Issue by nmichlo** [teddykoker/torchsort#23]
I am getting the following error after upgrading to torch 1.9

```
double free or corruption (!prev)
Aborted (core dumped)
```

**Reproduce**

```python3
import torchsort
import torch

torchsort.soft_rank(torch.randn(10, 10))
torchsort.soft_rank(torch.randn(10, 10).cuda())  # this too
```

```bash
python -c "import torchsort, torch; torchsort.soft_rank(torch.randn(10, 10))"
python -c "import torchsort, torch; torchsort.soft_rank(torch.randn(10, 10).cuda())"
```

**System Details**
```
Driver Version: 460.32.03
CUDA Version: 11.2
python: 3.8.10
Ubuntu 18.04.5 LTS x86_64
Kernel: 4.15.0-144-generic
```

**Comment by teddykoker** [comment]
Hey again Nathan,

[Running the CI with PyTorch 1.9](https://github.com/teddykoker/torchsort/runs/2895401089?check_suite_focus=true) doesn't encounter this issue. When I tried locally I got a weird cpython error, but reinstalling `torchsort` fixed this issue. I suspect that the extension must need to be recompiled again with the new PyTorch version, which can be triggered by reinstalling. You may need to run:
```bash
pip install --force-reinstall --no-cache-dir torchsort
```
to avoid using the cached object code. Let me know if this works!

**Comment by nmichlo** [comment]
Thank you for your quick response!

I tried setting up a new pyenv specifically for this, but I forgot the build would persist.

The `--force-reinstall --no-cache-dir` this time around did the trick!
