### ISSUE TITLE
differentiable top k indices

### ISSUE THREAD

**Issue by Chen-Cai-OSU** [teddykoker/torchsort#24]
Hello,

I am looking for the the work around of back prop through ```torch.topk``` . torch.topk return values and indices. It can backprop values but not indices (see [here](https://discuss.pytorch.org/t/use-topk-as-a-selection-but-fail-to-autograd/58004)). I was wondering can torchsort can somehow achieve this? Thank you so much!

**Comment by teddykoker** [comment]
Hi Chen Cai,

That can be achieved, see #19, specifically this comment: https://github.com/teddykoker/torchsort/issues/19#issuecomment-831525303

Let me know if you need any clarification!
