### ISSUE TITLE
RuntimeError: CUDA error: invalid device function

### ISSUE THREAD

**Issue by rekcahpassyla** [teddykoker/torchsort#27]
Hi there, thank you very much for this library- it has worked great for one of the problems I've encountered in research, at least on CPU. Now I am trying to get it to run on GPU; I have installed it from a git clone of this library and then `python setup.py install`. However, I'm running into this stack trace. Like others, I've tried to use the `spearmanr` example from the main README.md. 

I tried to look for other closed issues involving this to see if anyone else had run into it, but I haven't found any (or maybe I missed them?)

```
     34 def spearmanr(pred, target, **kw):
---> 35     pred = torchsort.soft_rank(pred, **kw)
     36     target = torchsort.soft_rank(target, **kw)
     37     pred = pred - pred.mean()

~/envs/pytorch1938/lib/python3.8/site-packages/torchsort-0.1.5-py3.8-linux-x86_64.egg/torchsort/ops.py in soft_rank(values, regularization, regularization_strength)
     38     if regularization not in ["l2", "kl"]:
     39         raise ValueError(f"'regularization' should be a 'l2' or 'kl'")
---> 40     return SoftRank.apply(values, regularization, regularization_strength)
     41 
     42 

~/envs/pytorch1938/lib/python3.8/site-packages/torchsort-0.1.5-py3.8-linux-x86_64.egg/torchsort/ops.py in forward(ctx, tensor, regularization, regularization_strength)
     94         if ctx.regularization == "l2":
     95             dual_sol = isotonic_l2[s.device.type](s - w)
---> 96             ret = (s - dual_sol).gather(1, inv_permutation)
     97             factor = torch.tensor(1.0, device=s.device)
     98         else:

RuntimeError: CUDA error: invalid device function
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```
Here is my system information:

```
$ uname -a
Linux xxx.xxx.ucl.ac.uk 4.15.0-143-generic #147-Ubuntu SMP Wed Apr 14 16:10:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

```

Here is my Python information (I am running anaconda - so this is an excerpt from `conda info`)

```
         python version : 3.8.10.final.0
       virtual packages : __cuda=11.2=0
                          __linux=4.15.0=0
                          __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
```

Many thanks!

**Comment by rekcahpassyla** [comment]
I've sorted myself out- It was because:

The version of `nvcc` on the machine I built, was cuda 10.0. The driver was 11.2

In case anyone else runs into this, all that was required was to upgrade the nvcc (by installing cuda 11.2 toolkit, to match the cuda 11.2 driver), and do the following

```
python setup.py clean --all
python setup.py install
```

**Comment by teddykoker** [comment]
Hi @rekcahpassyla, glad you got this sorted out! Thanks for sharing your solution :)
