### ISSUE TITLE
soft_rank has memory leak?

### ISSUE THREAD

**Issue by ashkan-leo** [teddykoker/torchsort#29]
Hi I have installed the main branch, and I'm seeing that the torchsort.soft_rank function is causing memory leaks. Looking at, nvidia-smi, it does not free up any memory and I see the following printed out over and over:

```
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
```

**Comment by teddykoker** [comment]
Hi! Would you be able to provide more details about the Pytorch version, python version, etc.? I have been able to reproduce this. There was a memory leak (see #15) for `soft_rank` (only when regularization=`l2`), but this was fixed in #16. If you have an older version you might need to reinstall. You can use:
```
pip install --force-reinstall --no-cache-dir torchsort
```
To ensure it recompiles the kernel.

**Comment by ashkan-leo** [comment]
I am using Python 3.9 and I have installed the git main branch using poetry like this:
```
torchsort = {git = "ssh://git@github.com/teddykoker/torchsort.git", rev = "main"}
```
I have to build from the git repo otherwise the cuda extensions don't get build.

**Comment by teddykoker** [comment]
It looks like the cuda file wasn't added to the PyPi release. I fixed this just now, you can install version 0.1.6

In terms of the memory leak, would you be able to provide an example such as:

```python
import subprocess as sp
import torch
import torchsort

pred = torch.randn(256, 3*64*64, requires_grad=True).cuda()

for i in range(100000):
    torchsort.soft_rank(pred, regularization="kl")
    # check the current GPU free memory
    print(i, ':', sp.check_output("nvidia-smi --query-gpu=memory.free --format=csv,noheader".split()).decode().strip())
```
That can reproduce the issue? Thanks!

**Comment by ashkan-leo** [comment]
I can confirm that the 0.1.6 release fixed the PyPi release. The cuda extension is built successfully. Thank you for fixing that!

**Comment by ashkan-leo** [comment]
For the memory leak, it turns out it was a bug in my data loader logic. 
I will close this issue.
Thanks a lot for making this excellent package!

**Comment by ashkan-leo** [comment]
Closing the issue
