### ISSUE TITLE
Does torchsort support fp16 training?

### ISSUE THREAD

**Issue by SkyAndCloud** [teddykoker/torchsort#30]
Hi, thank you for the efforts. I want to use torchsort in fp16 setting. It seems that torchsort doesn't support fp16 yet? Looking forward to your reply!

**Comment by teddykoker** [comment]
Hi! Apologies for the delay. Torchsort currently doesn't yet support fp16. You may be able to convert to fp32 just for the torchsort operation and leverage fp16 for the rest of the network. I am having trouble finding how to implement fp16 in custom CUDA kernels for PyTorch (I think I just need to replace the `AT_DISPATCH_FLOATING_TYPES` with `AT_DISPATCH_FLOATING_TYPES_AND_HALF`, but I'm not positive). I will work on it this weekend and let you know!

**Comment by teddykoker** [comment]
Added fp16 support in version 0.1.7! Install with:

```bash
pip install -U torchsort
```
