### ISSUE TITLE
Installation error on conda environment (and how to fix it)

### ISSUE THREAD

**Issue by levnikmyskin** [teddykoker/torchsort#35]
Hi!
First things first, thanks for this package! Now, it looks like in some linux systems the package does not compile with `pip install` in conda environments (to me it looks like it does not compile on colab as well though).  
In my case, the error was that the system compiler and the compiler used for installing `pytorch` via conda are different. I'm opening this issue just FYI (and because this will probably be helpful to others):  
if this happens, you should install the g++ compiler with `conda install -c conda-forge gxx_linux-64`, set the env variable `export CXX=/path/to/miniconda3/envs/env_name/bin/x86_64-conda_cos6-linux-gnu-g++`. If this still fails, export also the `LD_LIBRARY_PATH` env variable to `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/miniconda3/lib`.

**Comment by teddykoker** [comment]
Thanks @levnikmyskin, I'll add a note to the README!
