### ISSUE TITLE
Hi, NVIDIA CUDA version >= 11.4 does not seem to install successfully.

### ISSUE THREAD

**Issue by XiaoqiWang** [teddykoker/torchsort#51]
I tried to install the package in Tesla A100 and GeForce RTX 3090 with CUDA version 11.4 both failed. Can you provide some help please? Thank you very much!

**Comment by XiaoqiWang** [comment]
E:\conda\lib\site-packages\torch\include\pybind11\cast.h(1429): error: too few arguments for template template parameter "Tuple"
                detected during instantiation of class "pybind11::detail::tuple_caster<Tuple, Ts...> [with Tuple=std::pair, Ts=<T1, T2>]"
      (1507): here

      E:\conda\lib\site-packages\torch\include\pybind11\cast.h(1503): error: too few arguments for template template parameter "Tuple"
                detected during instantiation of class "pybind11::detail::tuple_caster<Tuple, Ts...> [with Tuple=std::pair, Ts=<T1, T2>]"
      (1507): here

      2 errors detected in the compilation of "torchsort/isotonic_cuda.cu".
      isotonic_cuda.cu
      error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.4\\bin\\nvcc.exe' failed with exit code 1

**Comment by teddykoker** [comment]
Hi @XiaoqiWang, what version of PyTorch do you have installed? I have been able to build torchsort just fine in 11.4 on my machine, but I wonder if a different pytorch version is causing the issue.

**Comment by XiaoqiWang** [comment]
Hi，thank you for your reply. My pytorch version is  1.11.0 + cu113.

**Comment by teddykoker** [comment]
I see you are on a windows system - what version is your c++ compiler? It seems there may be an issue with pybind and certain versions of visual studio and CUDA, see: https://github.com/facebookresearch/pytorch3d/issues/1024

**Comment by XiaoqiWang** [comment]
Thanks. I will try these solutions and get back to you as soon as possible.

**Comment by XiaoqiWang** [comment]
I successfully installed the package on a linux centos7 system, the system's g++ version requires higher than 5.0, otherwise the following error is reported: unrecognized command line option '-std=c++14'

I believe the previous issue was caused by the version of the window c++ compiler, not by the relatively high pytorch and cuda versions. （My C++ Compiler Version is 19.00.24210）

**Comment by teddykoker** [comment]
Great! Seems like there are some issues with windows and pytorch cuda extensions that may have caused the issue. Glad you were able to install it!
