### ISSUE TITLE
In Python 3.9, running 'torchsort' will report a error

### ISSUE THREAD

**Issue by pilgrimygy** [teddykoker/torchsort#53]
Specifically, when I use python 3.9, it will report this error:
```python
ImportError: /home/gyyang/anaconda3/lib/python3.9/site-packages/torchsort/isotonic_cpu.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC2ENS_14SourceLocationESs
```
But Python 3.8 is not such an error.

**Comment by teddykoker** [comment]
Hey @pilgrimygy. I added python 3.8, 3.9, and 3.10 to the CI tests; all tests are passing. Have you tried reinstalling with the new python version?

**Comment by pilgrimygy** [comment]
I will test it and give you feedback. Thanks you so much!

**Comment by XiaojunTan** [comment]
I fixed the problem by with 3steps:
1. pip cache remove torchsort
2. pip uninstall torchsort
3. pip install torchsort. 

Let me know if it also works for you.
