### ISSUE TITLE
[Error]pip install

### ISSUE THREAD

**Issue by Fan123456-c** [teddykoker/torchsort#82]
CUDA: 11.8
Torch: 1.12.0
Python: 3.7
When I used 'pip install torchsort', it printed:

Collecting torchsort
  Using cached torchsort-0.1.9.tar.gz (12 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: torch in ./lib/python3.7/site-packages (from torchsort) (1.12.0)
Requirement already satisfied: typing_extensions in ./lib/python3.7/site-packages (from torch->torchsort) (4.3.0)
Building wheels for collected packages: torchsort
  Building wheel for torchsort (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [39 lines of output]
      running bdist_wheel
      /home/lfan/lib/python3.7/site-packages/torch/utils/cpp_extension.py:411: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-37
      creating build/lib.linux-x86_64-cpython-37/torchsort
      copying torchsort/__init__.py -> build/lib.linux-x86_64-cpython-37/torchsort
      copying torchsort/ops.py -> build/lib.linux-x86_64-cpython-37/torchsort
      running egg_info
      writing torchsort.egg-info/PKG-INFO
      writing dependency_links to torchsort.egg-info/dependency_links.txt
      writing requirements to torchsort.egg-info/requires.txt
      writing top-level names to torchsort.egg-info/top_level.txt
      reading manifest file 'torchsort.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      writing manifest file 'torchsort.egg-info/SOURCES.txt'
      copying torchsort/isotonic_cpu.cpp -> build/lib.linux-x86_64-cpython-37/torchsort
      copying torchsort/isotonic_cuda.cu -> build/lib.linux-x86_64-cpython-37/torchsort
      running build_ext
      /home/lfan/lib/python3.7/site-packages/torch/utils/cpp_extension.py:813: UserWarning: The detected CUDA version (11.8) has a minor version mismatch with the version that was used to compile PyTorch (11.3). Most likely this shouldn't be a problem.
        warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
      /home/lfan/lib/python3.7/site-packages/torch/utils/cpp_extension.py:820: UserWarning: There are no g++ version bounds defined for CUDA version 11.8
        warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
      building 'torchsort.isotonic_cpu' extension
      creating build/temp.linux-x86_64-cpython-37
      creating build/temp.linux-x86_64-cpython-37/torchsort
      gcc -pthread -B /opt/anaconda1anaconda2anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/lfan/lib/python3.7/site-packages/torch/include -I/home/lfan/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/lfan/lib/python3.7/site-packages/torch/include/TH -I/home/lfan/lib/python3.7/site-packages/torch/include/THC -I/opt/anaconda1anaconda2anaconda3/include/python3.7m -c torchsort/isotonic_cpu.cpp -o build/temp.linux-x86_64-cpython-37/torchsort/isotonic_cpu.o -fopenmp -ffast-math -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1013\" -DTORCH_EXTENSION_NAME=isotonic_cpu -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
      cc1plus: warning: command-line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
      In file included from /home/lfan/lib/python3.7/site-packages/torch/include/torch/csrc/Device.h:3,
                       from /home/lfan/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/python.h:8,
                       from /home/lfan/lib/python3.7/site-packages/torch/include/torch/extension.h:6,
                       from torchsort/isotonic_cpu.cpp:32:
      /home/lfan/lib/python3.7/site-packages/torch/include/torch/csrc/python_headers.h:10:10: fatal error: Python.h: No such file or directory
         10 | #include <Python.h>
            |          ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for torchsort
  Running setup.py clean for torchsort
Failed to build torchsort
Installing collected packages: torchsort
  Running setup.py install for torchsort ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for torchsort did not run successfully.
  │ exit code: 1
  ╰─> [41 lines of output]
      running install
      /home/lfan/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        setuptools.SetuptoolsDeprecationWarning,
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-37
      creating build/lib.linux-x86_64-cpython-37/torchsort
      copying torchsort/__init__.py -> build/lib.linux-x86_64-cpython-37/torchsort
      copying torchsort/ops.py -> build/lib.linux-x86_64-cpython-37/torchsort
      running egg_info
      writing torchsort.egg-info/PKG-INFO
      writing dependency_links to torchsort.egg-info/dependency_links.txt
      writing requirements to torchsort.egg-info/requires.txt
      writing top-level names to torchsort.egg-info/top_level.txt
      /home/lfan/lib/python3.7/site-packages/torch/utils/cpp_extension.py:411: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      reading manifest file 'torchsort.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      writing manifest file 'torchsort.egg-info/SOURCES.txt'
      copying torchsort/isotonic_cpu.cpp -> build/lib.linux-x86_64-cpython-37/torchsort
      copying torchsort/isotonic_cuda.cu -> build/lib.linux-x86_64-cpython-37/torchsort
      running build_ext
      /home/lfan/lib/python3.7/site-packages/torch/utils/cpp_extension.py:813: UserWarning: The detected CUDA version (11.8) has a minor version mismatch with the version that was used to compile PyTorch (11.3). Most likely this shouldn't be a problem.
        warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
      /home/lfan/lib/python3.7/site-packages/torch/utils/cpp_extension.py:820: UserWarning: There are no g++ version bounds defined for CUDA version 11.8
        warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
      building 'torchsort.isotonic_cpu' extension
      creating build/temp.linux-x86_64-cpython-37
      creating build/temp.linux-x86_64-cpython-37/torchsort
      gcc -pthread -B /opt/anaconda1anaconda2anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/lfan/lib/python3.7/site-packages/torch/include -I/home/lfan/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/lfan/lib/python3.7/site-packages/torch/include/TH -I/home/lfan/lib/python3.7/site-packages/torch/include/THC -I/opt/anaconda1anaconda2anaconda3/include/python3.7m -c torchsort/isotonic_cpu.cpp -o build/temp.linux-x86_64-cpython-37/torchsort/isotonic_cpu.o -fopenmp -ffast-math -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1013\" -DTORCH_EXTENSION_NAME=isotonic_cpu -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
      cc1plus: warning: command-line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
      In file included from /home/lfan/lib/python3.7/site-packages/torch/include/torch/csrc/Device.h:3,
                       from /home/lfan/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/python.h:8,
                       from /home/lfan/lib/python3.7/site-packages/torch/include/torch/extension.h:6,
                       from torchsort/isotonic_cpu.cpp:32:
      /home/lfan/lib/python3.7/site-packages/torch/include/torch/csrc/python_headers.h:10:10: fatal error: Python.h: No such file or directory
         10 | #include <Python.h>
            |          ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> torchsort

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by teddykoker** [comment]
Hi @Fan123456-c,

Please see the portion of the error message “fatal error: Python.h: No such file or directory”. A some google searching of this message should be able t resolve this depending on your machine, such as this [stackoverflow](https://stackoverflow.com/a/21530768).
